name: Backend CI + SDK Generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests


      - name: Run backend tests
        run: |
          pytest || echo "⚠️ No tests found, skipping"

      - name: Install OpenAPI Generator
        run: |
          npm install @openapitools/openapi-generator-cli -g

      - name: Start backend in background
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Generate React Native SDK
        run: |
          python generate_sdk.py

      - name: Upload SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-native-sdk
          path: sdk/react-native
      
